services:
  web:
    image: ghcr.io/tsaimatthew/homework-website:main
    volumes:
      - ./static:/var/www/homework-website/static
      - ./media:/var/www/html/media
    ports:
      - "8000:8000"
    env_file:
      - .env
    restart: always
